import { Printer, TonerItem, Movement, Alert } from './types';
import { v4 as uuidv4 } from 'uuid';

export const initialPrinters: Printer[] = [
  {
    id: uuidv4(),
    name: 'HP LaserJet Pro M404',
    location: 'Oficina Principal - Piso 2',
    department: 'Administración',
    model: 'HP LaserJet Pro M404dn',
    status: 'active',
    tonerModel: 'CF258A',
    lastMaintenance: '2025-11-15',
    totalPages: 12450,
  },
  {
    id: uuidv4(),
    name: 'Brother HL-L2350DW',
    location: 'Contabilidad - Piso 1',
    department: 'Contabilidad',
    model: 'Brother HL-L2350DW',
    status: 'active',
    tonerModel: 'TN-760',
    lastMaintenance: '2025-12-01',
    totalPages: 8920,
  },
  {
    id: uuidv4(),
    name: 'Canon imageCLASS MF269dw',
    location: 'Recursos Humanos - Piso 3',
    department: 'RRHH',
    model: 'Canon MF269dw',
    status: 'maintenance',
    tonerModel: 'Canon 057',
    lastMaintenance: '2026-01-10',
    totalPages: 15670,
  },
  {
    id: uuidv4(),
    name: 'Samsung Xpress M2070W',
    location: 'Marketing - Piso 2',
    department: 'Marketing',
    model: 'Samsung Xpress M2070W',
    status: 'active',
    tonerModel: 'MLT-D111S',
    lastMaintenance: '2025-10-20',
    totalPages: 6340,
  },
  {
    id: uuidv4(),
    name: 'Epson EcoTank L3250',
    location: 'Dirección - Piso 4',
    department: 'Dirección',
    model: 'Epson EcoTank L3250',
    status: 'inactive',
    tonerModel: 'T544',
    lastMaintenance: '2025-09-05',
    totalPages: 22100,
  },
  {
    id: uuidv4(),
    name: 'HP Color LaserJet Pro M479',
    location: 'Ventas - Piso 1',
    department: 'Ventas',
    model: 'HP Color LaserJet Pro M479fdw',
    status: 'active',
    tonerModel: 'W2040A',
    lastMaintenance: '2025-12-20',
    totalPages: 9870,
  },
];

export const initialToners: TonerItem[] = [
  {
    id: uuidv4(),
    model: 'CF258A',
    brand: 'HP',
    color: 'black',
    stock: 5,
    minStock: 3,
    maxStock: 15,
    unitPrice: 85.00,
    supplier: 'Distribuidora Tóner Pro',
    lastRestock: '2026-01-05',
  },
  {
    id: uuidv4(),
    model: 'TN-760',
    brand: 'Brother',
    color: 'black',
    stock: 2,
    minStock: 3,
    maxStock: 12,
    unitPrice: 72.50,
    supplier: 'Office Supplies Corp',
    lastRestock: '2025-12-15',
  },
  {
    id: uuidv4(),
    model: 'Canon 057',
    brand: 'Canon',
    color: 'black',
    stock: 8,
    minStock: 2,
    maxStock: 10,
    unitPrice: 95.00,
    supplier: 'Canon Distribuciones',
    lastRestock: '2026-01-10',
  },
  {
    id: uuidv4(),
    model: 'MLT-D111S',
    brand: 'Samsung',
    color: 'black',
    stock: 1,
    minStock: 2,
    maxStock: 8,
    unitPrice: 55.00,
    supplier: 'Distribuidora Tóner Pro',
    lastRestock: '2025-11-28',
  },
  {
    id: uuidv4(),
    model: 'T544',
    brand: 'Epson',
    color: 'black',
    stock: 12,
    minStock: 4,
    maxStock: 20,
    unitPrice: 18.50,
    supplier: 'Epson Direct',
    lastRestock: '2026-01-08',
  },
  {
    id: uuidv4(),
    model: 'W2040A',
    brand: 'HP',
    color: 'black',
    stock: 3,
    minStock: 3,
    maxStock: 15,
    unitPrice: 110.00,
    supplier: 'Distribuidora Tóner Pro',
    lastRestock: '2025-12-20',
  },
  {
    id: uuidv4(),
    model: 'W2041A',
    brand: 'HP',
    color: 'cyan',
    stock: 4,
    minStock: 2,
    maxStock: 10,
    unitPrice: 125.00,
    supplier: 'Distribuidora Tóner Pro',
    lastRestock: '2025-12-20',
  },
  {
    id: uuidv4(),
    model: 'W2043A',
    brand: 'HP',
    color: 'yellow',
    stock: 2,
    minStock: 2,
    maxStock: 10,
    unitPrice: 125.00,
    supplier: 'Distribuidora Tóner Pro',
    lastRestock: '2025-12-20',
  },
];

export const initialMovements: Movement[] = [
  {
    id: uuidv4(),
    type: 'delivery',
    tonerId: '',
    tonerModel: 'CF258A',
    printerId: '',
    printerName: 'HP LaserJet Pro M404',
    quantity: 1,
    date: '2026-01-15',
    user: 'Carlos Méndez',
    notes: 'Reemplazo programado',
  },
  {
    id: uuidv4(),
    type: 'restock',
    tonerId: '',
    tonerModel: 'Canon 057',
    quantity: 5,
    date: '2026-01-10',
    user: 'Ana García',
    notes: 'Pedido #2026-001',
  },
  {
    id: uuidv4(),
    type: 'delivery',
    tonerId: '',
    tonerModel: 'TN-760',
    printerId: '',
    printerName: 'Brother HL-L2350DW',
    quantity: 1,
    date: '2026-01-08',
    user: 'Carlos Méndez',
    notes: 'Nivel bajo detectado',
  },
  {
    id: uuidv4(),
    type: 'restock',
    tonerId: '',
    tonerModel: 'T544',
    quantity: 10,
    date: '2026-01-08',
    user: 'Ana García',
    notes: 'Reposición mensual',
  },
  {
    id: uuidv4(),
    type: 'delivery',
    tonerId: '',
    tonerModel: 'W2040A',
    printerId: '',
    printerName: 'HP Color LaserJet Pro M479',
    quantity: 1,
    date: '2026-01-05',
    user: 'Roberto Sánchez',
    notes: 'Cambio preventivo',
  },
  {
    id: uuidv4(),
    type: 'return',
    tonerId: '',
    tonerModel: 'MLT-D111S',
    quantity: 1,
    date: '2026-01-03',
    user: 'Carlos Méndez',
    notes: 'Tóner incompatible, se devuelve al almacén',
  },
  {
    id: uuidv4(),
    type: 'disposal',
    tonerId: '',
    tonerModel: 'CF258A',
    quantity: 1,
    date: '2025-12-28',
    user: 'Ana García',
    notes: 'Tóner defectuoso, enviado a reciclaje',
  },
  {
    id: uuidv4(),
    type: 'restock',
    tonerId: '',
    tonerModel: 'W2040A',
    quantity: 6,
    date: '2025-12-20',
    user: 'Ana García',
    notes: 'Pedido urgente #2025-045',
  },
  {
    id: uuidv4(),
    type: 'delivery',
    tonerId: '',
    tonerModel: 'CF258A',
    printerId: '',
    printerName: 'HP LaserJet Pro M404',
    quantity: 1,
    date: '2025-12-18',
    user: 'Roberto Sánchez',
    notes: 'Reemplazo de emergencia',
  },
  {
    id: uuidv4(),
    type: 'restock',
    tonerId: '',
    tonerModel: 'TN-760',
    quantity: 4,
    date: '2025-12-15',
    user: 'Ana García',
    notes: 'Pedido trimestral',
  },
];

export const initialAlerts: Alert[] = [
  {
    id: uuidv4(),
    type: 'low_stock',
    message: 'Stock bajo: TN-760 (Brother) - Solo 2 unidades disponibles',
    severity: 'high',
    date: '2026-01-15',
    read: false,
  },
  {
    id: uuidv4(),
    type: 'low_stock',
    message: 'Stock bajo: MLT-D111S (Samsung) - Solo 1 unidad disponible',
    severity: 'high',
    date: '2026-01-14',
    read: false,
  },
  {
    id: uuidv4(),
    type: 'maintenance',
    message: 'Mantenimiento próximo: Canon imageCLASS MF269dw - En mantenimiento',
    severity: 'medium',
    date: '2026-01-10',
    read: false,
  },
  {
    id: uuidv4(),
    type: 'low_stock',
    message: 'Stock bajo: W2040A (HP) - Al nivel mínimo (3 unidades)',
    severity: 'medium',
    date: '2026-01-08',
    read: true,
  },
  {
    id: uuidv4(),
    type: 'info',
    message: 'Reporte mensual generado exitosamente',
    severity: 'low',
    date: '2026-01-01',
    read: true,
  },
];
